config/routes.rb
FirstApp::Application.routes.draw do

  root to: 'topics#index'

  match "/users/login" => "users#login"
  match "/users/logout" => "users#logout"
  match "/users/audit/:id" => "users#audit"
  match "/replies/create" => "replies#create"

  resources :users

  resources :replies

  resources :topics

  resources :forecasters

  mount Ckeditor::Engine => '/ckeditor'

end

app/models/reply.rb
class Reply < ActiveRecord::Base
  attr_accessible :content, :is_valid, :top, :topic_id, :user_id
  belongs_to :topic
  belongs_to :user
end

app/controllers/replies_controller.rb
# -*- coding: utf-8 -*-
class RepliesController < ApplicationController
  before_filter :user_online, :only => [:create, :edit, :delete]
  # GET /replies
  # GET /replies.json
  def index
    @replies = Reply.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @replies }
    end
  end

  # GET /replies/1
  # GET /replies/1.json
  def show
    @reply = Reply.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @reply }
    end
  end

  # GET /replies/new
  # GET /replies/new.json
  def new
    @reply = Reply.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @reply }
    end
  end

  # GET /replies/1/edit
  def edit
    @reply = Reply.find(params[:id])
  end

  # POST /replies
  # POST /replies.json
  def create
    @reply = Reply.new(params[:reply])
    @reply.user_id = session[:current_user].id

    respond_to do |format|
      if @reply.save
        @reply.topic.add_reply_count
        format.html { redirect_to @reply.topic, notice: 'Reply was successfully created.' }
        format.json { render json: @reply, status: :created, location: @reply }
      else
        format.html { render action: "new" }
        format.json { render json: @reply.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /replies/1
  # PUT /replies/1.json
  def update
    @reply = Reply.find(params[:id])

    respond_to do |format|
      if @reply.update_attributes(params[:reply])
        format.html { redirect_to @reply, notice: 'Reply was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @reply.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /replies/1
  # DELETE /replies/1.json
  def destroy
    @reply = Reply.find(params[:id])
    @reply.destroy

    respond_to do |format|
      format.html { redirect_to replies_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/replies_helper.rb
module RepliesHelper
end

app/views/replies/_form.html.erb
<%= form_for(@reply) do |f| %>
  <% if @reply.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@reply.errors.count, "error") %> prohibited this reply from being saved:</h2>

      <ul>
      <% @reply.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :topic_id %><br />
    <%= f.number_field :topic_id %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :is_valid %><br />
    <%= f.number_field :is_valid %>
  </div>
  <div class="field">
    <%= f.label :top %><br />
    <%= f.number_field :top %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/replies/edit.html.erb
<h1>Editing reply</h1>

<%= render 'form' %>

<%= link_to 'Show', @reply %> |
<%= link_to 'Back', replies_path %>

app/views/replies/index.html.erb
<h1>Listing replies</h1>

<table>
  <tr>
    <th>Topic</th>
    <th>Content</th>
    <th>User</th>
    <th>Is valid</th>
    <th>Top</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @replies.each do |reply| %>
  <tr>
    <td><%= reply.topic_id %></td>
    <td><%= reply.content %></td>
    <td><%= reply.user_id %></td>
    <td><%= reply.is_valid %></td>
    <td><%= reply.top %></td>
    <td><%= link_to 'Show', reply %></td>
    <td><%= link_to 'Edit', edit_reply_path(reply) %></td>
    <td><%= link_to 'Destroy', reply, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Reply', new_reply_path %>

app/views/replies/new.html.erb
<h1>New reply</h1>

<%= render 'form' %>

<%= link_to 'Back', replies_path %>

app/views/replies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Topic:</b>
  <%= @reply.topic_id %>
</p>

<p>
  <b>Content:</b>
  <%= @reply.content %>
</p>

<p>
  <b>User:</b>
  <%= @reply.user_id %>
</p>

<p>
  <b>Is valid:</b>
  <%= @reply.is_valid %>
</p>

<p>
  <b>Top:</b>
  <%= @reply.top %>
</p>


<%= link_to 'Edit', edit_reply_path(@reply) %> |
<%= link_to 'Back', replies_path %>