config/routes.rb
FirstApp::Application.routes.draw do

  root to: 'topics#index'

  match "/users/login" => "users#login"
  match "/users/logout" => "users#logout"
  match "/users/audit/:id" => "users#audit"
  match "/replies/create" => "replies#create"

  resources :users

  resources :replies

  resources :topics

  resources :forecasters

  mount Ckeditor::Engine => '/ckeditor'

end

app/models/topic.rb
class Topic < ActiveRecord::Base
  attr_accessible :category_id, :content, :essence, :feedback, :replies, :title, :top, :user_id, :valid, :views
  belongs_to :user
  has_many :replies
  validates :title, :length => { :min => 2, :maximum => 20 }

  def add_reply_count
  	self.reply_count += 1
  	self.save
  end
end

app/controllers/topics_controller.rb
# -*- coding: utf-8 -*-
class TopicsController < ApplicationController
  before_filter :authorize, :only => [:edit, :delete]
  before_filter :user_online, :only => [:new, :create, :edit]
  # GET /topics
  # GET /topics.json
  def index
    @topics = Topic.where(:state => 1).paginate(:page => params[:page], :per_page => 10).order('updated_at DESC')
    @forecasters = User.where(:is_forecaster=>1, :state => 1).order('id DESC').limit(10)
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @topics }
    end
  end

  # GET /topics/1
  # GET /topics/1.json
  def show
    @topic = Topic.find(params[:id])
    add_view (@topic) if @topic
    @reply = Reply.new
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @topic }
    end
  end

  # GET /topics/new
  # GET /topics/new.json
  def new
    @topic = Topic.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @topic }
    end
  end

  # GET /topics/1/edit
  def edit
    @topic = Topic.find(params[:id])
  end

  # POST /topics
  # POST /topics.json
  def create
    @topic = Topic.new(params[:topic])
    @topic.feedback = 0
    @topic.state = 1
    @topic.views = 0
    @topic.top = 0
    @topic.user_id = session[:current_user].id
    @topic.essence = 0
    respond_to do |format|
      if @topic.save
        format.html { redirect_to @topic, notice: 'Topic was successfully created.' }
        format.json { render json: @topic, status: :created, location: @topic }
      else
        format.html { render action: "new" }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /topics/1
  # PUT /topics/1.json
  def update
    @topic = Topic.find(params[:id])

    respond_to do |format|
      if @topic.update_attributes(params[:topic])
        format.html { redirect_to @topic, notice: 'Topic was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /topics/1
  # DELETE /topics/1.json
  def destroy
    @topic = Topic.find(params[:id])
    @topic.destroy

    respond_to do |format|
      format.html { redirect_to topics_url }
      format.json { head :no_content }
    end
  end

  def add_view (topic)
    topic.views = topic.views + 1 if topic
    topic.save
  end
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/_form.html.erb
<%= form_for(@topic) do |f| %>
  <% if @topic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@topic.errors.count, "error") %> prohibited this topic from being saved:</h2>

      <ul>
      <% @topic.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :category_id %><br />
    <%= f.number_field :category_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/topics/edit.html.erb
<h1>Editing topic</h1>

<%= render 'form' %>

<%= link_to 'Show', @topic %> |
<%= link_to 'Back', topics_path %>

app/views/topics/index.html.erb
<% provide(:title, '帖子列表') %>
<div class="row">
  <div class="col-*-12">
    <button type="button" class="btn btn-success" onclick="javascript:window.open('/topics/new');">发帖</button>
  </div>
</div>
<div class="col-md-10 pad10 col-md-re">
  <div class="panel-content-redo marginbtm25">
    <table class="table table-hover">
    <!-- <table class="respon-table" border="0" cellpadding="0" cellspacing="0" width="100%"> -->
      <tbody><tr>
        <th class="col-xs-12 col-sm-6 col-md-6 cate-list">标题</th>
        <th class="col-xs-12 col-sm-2 col-md-2 hidden-xs cate-list">回复/阅读</th>
        <th class="col-xs-12 col-sm-2 col-md-2 hidden-xs cate-list">作者</th>
        <th class="col-xs-12 col-sm-2 col-md-2 hidden-xs cate-list">最后回复</th>
      </tr>
      <% if @topics and @topics.size>0 %>
          <% @topics.each do |topic| %>
          <tr name="show_more_topics" forum_id="145" top="1">
            <td class="col-xs-12 col-sm-6 col-md-6">
              <a href="/topics/<%=topic.id %>" target="_blank"><%=topic.title %></a>
            </td>
            <td class="col-xs-12 col-sm-2 col-md-2 hidden-xs"><%=topic.reply_count %>/<%=topic.views %></td>
            <td class="col-xs-12 col-sm-2 col-md-2 hidden-xs table-timecol">
              <a href="/users/<%=topic.user_id %>" target="_blank"><%=topic.user.name %></a>
              <div><%=topic.created_at.strftime("%F") %></div>
            </td>
            <td class="col-xs-12 col-sm-2 col-md-2 hidden-xs table-timecol">
              <a href="/users/<%=topic.user_id %>" target="_blank"><%=topic.user.name %></a>
              <div><%=topic.updated_at.strftime("%F") %></div>
            </td>
          </tr>
          <% end %>
      <% end %>
      <%= will_paginate @topics %>
      </tbody>
    </table>
  </div>
</div>

<div class="col-md-2 pad2 col-md-re">
  <div class="panel panel-default">
  <div class="panel-heading">新注册的老师</div>
  <div class="panel-body">
    <%if @forecasters.size > 0 
        @forecasters.each do |forecaster|
    %>
        <%=forecaster.name %>
    <%  end 
      end %>
  </div>
</div>
</div>

app/views/topics/new.html.erb
<% provide(:title, '新建帖子') %>
<%= link_to 'Back', topics_path %>

<%= form_for @topic,:html => {:role => 'form'} do |f| %>
  <div class="form-group">
    <label for="topic_title" class="col-sm-2 control-label">帖子标题</label>
    <div class="col-sm-10">
      <%= f.text_field :title, :class=>"form-control", :placeholder=>"输入2~50个字符" %>
    </div>
  </div>
  <div class="form-group">
    <label for="topic_content" class="col-sm-2 control-label">帖子内容</label>
    <div class="col-sm-10">
      <div class="field" > 
        <%= f.cktext_area :content,  :toolbar => 'Full', :width => 900, :height => 400 %>  
      </div>
    </div>
  </div>
  <!-- <div class="form-group">
    <label for="topic_category_id" class="col-sm-2 control-label">栏目</label>
    <div class="col-sm-10">
      </%= f.text_field :category_id, :class=>"form-control" %>
    </div>
  </div> -->
  <div class="form-group">
  	<div class="col-sm-12">
      <button type="submit" class="btn btn-default">创建帖子</button>
    </div>
  </div>
<% end %>

app/views/topics/show.html.erb
<% provide(:title, @topic.title) %>
<div class="container container-main">

<div class="col-md-12 col-md-re hidden-xs">
  <div>
    <a href="/"><span>首页&nbsp;</span></a><i>&gt;&nbsp;</i>
    <!-- <a href="#"><%=@topic.category_id %></a> <i>&gt;&nbsp;</i> -->
    <%=@topic.title %>
  </div>
</div>
<div class="col-md-12 col-md-re replybtntop mb15 clearfix">
  <!-- 分页与发贴回复按钮组 开始 -->
  <!-- 分页 开始 -->
  <div class="col-md-10 col-sm-8 col-xs-8 padnone">
    <div class="pagebox hidden-xs"></div>
  </div>
  <!-- 分页 结束 -->
  <!-- 回复与发贴按钮组 开始 -->
  <div class="fr btn-group">
      <a href="javascript:void(0);" rel="nofollow" onclick="javascript:replay('楼主','环球电子', '80128', 1)" data-remote="true" data-type="script" class="visible-md visible-lg btn btn-success btn-replys">回复</a>
      <a data-type="script" data-remote="true" class="btn btn-success clearfix" href="javascript:void(0);">发帖</a>
    </div>
  </div>
  <!-- 回复与发贴按钮组 结束 -->
</div>
<!-- 分页与发贴回复按钮组 结束 -->
<!-- 主贴的详情展示 开始 -->
  <div class="col-md-12 pad10 col-md-re" desc="topic">
  <div class="clearfix marginbtm40">
    <div class="col-md-2 col-sm-2 hidden-xs">
      <div class="mb10">
        <a href="/users/<%=@topic.user.id %>" target="_blank"><%=@topic.user.name %></a>
          <span class="glyphicon glyphicon-certificate" title="当前离线"></span>
      </div>
      <div class="member-avatar mb10">
        <div id="user_info" topic_id="<%=@topic.id %>">
          <a href="/users/<%=@topic.user.id %>"><img id="user_image_80128" class="avatar" src="/images/user/medium/0.gif" alt="<%=@topic.user.name %>"></a>

        </div>
      </div>
      <!-- <p class="fans-space">积分：<strong>9</strong></p>
      <p class="fans-space">金币：<strong>14</strong></p> -->
    </div>
    <!-- 左侧的用户信息显示 结束 -->
    <!-- 右侧的主贴详细信息显示 开始 -->
    <div class="col-md-10 col-sm-10 col-xs-12 panel-content-redos">
    <!-- 主贴标题 手机上显示h4的标题 其它显示h2 -->
    <i class="roadtips hidden-xs"></i>
    <div class="text-center">
      <h4 style="text-align:left;bolder;"><%=@topic.title %></h4>
    </div>
    <!--
      发贴人信息 手机上显示发贴人的头像、昵称及发帖时间
      电脑上显示 阅读回复数 以及 只看TA
    -->
    <div class="mb20 clearfix">
      <div class="col-xs-10 col-sm-10 hidden-lg hidden-md hidden-sm padnone clearfix">
        <div class="fl member-avatar padnone "><a href="/users/<%=@topic.user.id %>"><img id="user_image_80128" class="avatar" src="/images/user/small/0.gif" alt="/users/<%=@topic.user.name %>"></a></div>
        <div class="fl ml20">
          <div class="mb5"><a href="/users/<%=@topic.user.id %>" target="_blank"><%=@topic.user.name %></a>
              <span class="glyphicon glyphicon-certificate" title="当前离线"></span>
          </div>
          <div><%=@topic.created_at.strftime("%F") %></div>
        </div>
      </div>
      <div class="col-xs-2 col-sm-2 text-right hidden-lg hidden-md hidden-sm padnone clearfix">
        <span class="floorsm">1F</span>
      </div>
      <div class="col-md-10 col-sm-10 padnone hidden-xs hidden-sm mb15">
        <span class="mr10">发表于<%=@topic.created_at.strftime("%F") %></span>
        <span class="mr10"><span class="glyphicon glyphicon-eye-open"></span>&nbsp;&nbsp;<%=@topic.views %></span>
        <span class="mr10"><span class="glyphicon glyphicon-comment"></span>&nbsp;&nbsp;<%=@topic.reply_count %></span>
      </div>
    </div>
    <!-- 主贴内容 -->
    <div class="col-*-12 main-contents clearfix">
      <%=@topic.content.html_safe %>
    </div>
    
    <!-- 用户革新签名 -->
    <!-- 百度分享以及回复与举报 -->
    <div class="col-*-12 padnone clearfix mt20 border-toppad border-toppad-re">
      <div class="col-md-10 col-sm-10 col-xs-10 padnone">
        <!-- Baidu Button BEGIN-->
        <div id="bdshare" class="fl mt5 hidden-xs bdshare_t bds_tools get-codes-bdshare">
          <span class="bds_more">分享到：</span>
          <a href="#" title="分享到新浪微博" class="bds_tsina"></a>
          <a href="#" title="分享到QQ空间" class="bds_qzone"></a>
          <a href="#" title="分享到腾讯微博" class="bds_tqq"></a>
          <a href="#" title="分享到人人网" class="bds_renren"></a>
          <a title="累计分享0次" href="#" class="shareCount">0</a>
        </div>
        <script src="http://bdimg.share.baidu.com/static/js/bds_s_v2.js?cdnversion=385142" type="text/javascript" id="bdshare_js" data="type=tools&amp;uid=2743551"></script>
        
        <script type="text/javascript">
          document.getElementById("bdshell_js").src = "http://bdimg.share.baidu.com/static/js/shell_v2.js?cdnversion="+Math.ceil(new Date()/3600000)
        </script>
        <!-- Baidu Button END -->
      </div>
      <div class="col-md-2 col-sm-2 col-xs-2 text-right padnone">
            <a href="javascript:void(0);" rel="nofollow" onclick="javascript:reply('楼主','环球电子', '80128', 1)" data-remote="true" data-type="script" class="visible-md visible-lg">回复</a>
            <a class="visible-xs" desc="reply_topic" href="javascript:void(0);" rel="nofollow" floor="楼主" nick="环球电子" u_id="80128" f_type="1">回复</a>
            <a class="visible-sm" desc="reply_topic_pad" href="javascript:void(0);" rel="nofollow" floor="楼主" nick="环球电子" u_id="80128" f_type="1">回复</a>
      </div>
    </div>
    </div>
    <!-- 右侧的主贴详细信息显示 结束 -->
  </div>
  </div>
<!-- 主贴的详情展示 结束 -->
<!-- 回复的详情展示 开始 -->
<% if @topic.replies 
     i = 1
     @topic.replies.each do |reply| %>
<div class="col-md-12 pad10 col-md-re clearfix" desc="replies" id="show_replies">
  <div class="clearfix" created_at="<%=reply.created_at %>" name="more_replies" topic_id="<%=reply.topic.id %>">
  <!-- 左侧的用户信息显示 开始 -->
  <div class="col-md-2 col-sm-2 hidden-xs">
    <div><a name="d08kkrykorkiiw"></a></div>
    <div class="mb10">
      <a href="/users/"+"<%=reply.user.id %>" target="_blank"><%=reply.user.name %></a>
        <span class="glyphicon glyphicon-certificate" title="当前离线"></span>
    </div>
    <div class="">
      <div class="clearfix">
        <div class="col-md-2"></div>
        <div class="col-md-10">
          <div class="clearfix"></div>
          <div class="clearfix"></div>
        </div>
      </div>
      <div class="mb10 member-avatar">
        <div reply_id="<%=reply.id %>">
          <a href="/users/<%=reply.user.id %>">
            <img id="user_image_51133" class="avatar" src="/images/user/medium/0.gif" alt="<%=reply.user.name %>"></a>
        </div>
      </div>
      <!-- <p class="fans-space">积分：<strong>71</strong></p>
      <p class="fans-space">金币：<strong>40870</strong></p> -->
    </div>
  </div>
  <!-- 左侧的用户信息显示 结束 -->
  <div class="col-md-10 col-sm-10 col-xs-12 panel-content-redo marginbtm40 posr">
    <i class="roadtips hidden-xs"></i>
    <div class="clearfix">
      <div class="col-xs-10 padnone hidden-lg hidden-md hidden-sm">
        <div class="fl member-avatar"><a href="/users/<%=reply.user.id %>">
          <img id="user_image_51133" class="avatar" src="/images/user/small/0.gif" alt="<%=reply.user.name %>"></a></div>
        <div class="fl ml20">
          <div class="mb5"><a href="/users/<%=reply.user.id %>" target="_blank"><%=reply.user.name %></a>
              <span class="glyphicon glyphicon-certificate" title="当前离线"></span>
          </div>
          <div><%=reply.created_at.strftime("%F") %></div>
        </div>

      </div>
      <div class="col-xs-2 padnone hidden-lg hidden-md hidden-sm">
        <div class="floorsm text-right"><%=i+1 %>F</div>
      </div>
      <div class="col-md-10 col-sm-10 padnone hidden-xs">
        <span>发表于&nbsp;<%=reply.created_at.strftime("%F") %></span>
      </div>
      <div class="col-md-2 col-sm-2 padnone posr hidden-xs clearfix">
        <span class="floornum"><%=i+1 %>F</span>
      </div>
    </div>
    <div class="col-*-12 flootourer min-height2" id="reply_<%=reply.id%>">
      <%=reply.content.html_safe %>
    </div>
    <div class="col-*-12 padnone clearfix mt10 border-toppad">
      <div class="col-md-10 col-sm-10 col-xs-10 padnone"></div>
      <div class="col-md-2 col-sm-2 col-xs-2 text-right padnone">
            <a class="visible-md visible-lg" href="javascript:void(0);" rel="nofollow" onclick="javascript:void replay('2楼','<%=reply.user.name %>', '<%=reply.user.id %>', 1)">回复</a>
            <a class="visible-xs" href="javascript:void(0);" desc="reply_others" rel="nofollow" floor="2楼" nick="<%=reply.user.name %>" u_id="<%=reply.user.id %>" f_type="1">回复</a>
            <a class="visible-sm" href="javascript:void(0);" desc="reply_others_pad" rel="nofollow" floor="2楼" nick="<%=reply.user.name %>" u_id="<%=reply.user.id %>" f_type="1">回复</a>
      </div>
    </div>
    <div class="col-*-12 padnone text-right hidden-xs">
    </div>
  </div>
  </div>
</div>
<% 
    i=i+1  
    end 
  end   %>
<!-- 回复的详情展示 结束 -->
<!-- 分页与发贴回复按钮组 开始 -->
<div class="col-md-12 marb20 willpaginates clearfix" desc="willpaginate">
  <!-- 分页与发贴回复按钮组 开始 -->
  <!-- 分页 开始 -->
  <div class="col-md-10 col-sm-8 col-xs-8 padnone">
    <div class="pagebox hidden-xs"></div>
  </div>
  <!-- 分页 结束 -->
  <!-- 回复与发贴按钮组 开始 -->
  <div class="fr btn-group hidden-xs">
      <a href="javascript:void(0);" rel="nofollow" onclick="javascript:replay('楼主','环球电子', '80128', 1)" data-remote="true" data-type="script" class="visible-md visible-lg btn btn-success btn-replys">回复</a>
      <a class="visible-xs btn btn-success btn-replys" desc="reply_topic" href="javascript:void(0);" rel="nofollow" floor="楼主" nick="环球电子" u_id="80128" f_type="1">回复</a>
      <a class="visible-sm btn btn-success btn-replys" desc="reply_topic_pad" href="javascript:void(0);" rel="nofollow" floor="楼主" nick="环球电子" u_id="80128" f_type="1">回复</a>
    <div class="newtopiclink mt0 hidden-xs">
      <a data-type="script" data-remote="true" class="btn btn-success clearfix" href="javascript:void(0);">发帖</a>
    </div>
  </div>
  <!-- 回复与发贴按钮组 结束 -->
</div>
<!-- 分页与发贴回复按钮组 结束 -->
  <div class="col-md-12 pad10 mb20"><button class="visible-xs moreormore" id="more_replies">查看更多</button></div>

  <div class="col-md-12 hidden-xs" desc="">
    <div class="quickReply"><a name="add"></a>
      <div class="panel panel-success panel-reply-redo marginbtm30">
        <div class="panel-heading">
          <h3 class="caption-panel-title">回复该帖</h3>
            <span>（<span class="required">*</span>为必填项）</span>
        </div>

        <!-- <form class="form-horizontal" role="form" id="post_form" method="post" action="/replies/create" accept-charset="UTF-8"> -->
        <%= form_for @reply,:html => {:role => 'form', :class=>'form-horizontal'} do |f| %>
          <input id="reply_topic_id" type="hidden" value="<%=@topic.id %>" name="reply[topic_id]"></input>
          <input id="topic_user_id" type="hidden" value="66759" name="topic_user_id"></input>
          <div class="form-group">
            <label for="reply_content" class="col-sm-2 control-label">内容</label>
            <div class="col-sm-10">
              <div class="field" > 
                <%= f.cktext_area :content, :toolbar=>'Full',:width=>800,:height=>400 %>  
              </div>
            </div>
          </div>
          <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
              <button type="submit" class="btn btn-default">发表回复</button>
            </div>
          </div>
          <% end -%>
        <!-- </form> -->
      </div>
    </div>
  </div>
</div>
<!--返回顶部-->
  <div class="hidden-xs">
    <div style="display: none; top: 538px; left: 1163px;" class="goTop"><a href="javascript:;" rel="nofollow"></a></div>
  </div>
</div>